<a href="https://colab.research.google.com/github/Satya-slav/ML_zoomcamp-2026/blob/main/introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

<module 'numpy' from '/usr/local/lib/python3.13/dist-packages/numpy/__init__.py'>

creating arrays

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10,514)

array([514, 514, 514, 514, 514, 514, 514, 514, 514, 514])

In [6]:
a = ([1,2,3,4,6])
a

[1, 2, 3, 4, 6]

In [7]:
a[2]

3

In [8]:
a[-1]

6

In [11]:
a[-1] = 7
a

[1, 2, 3, 4, 7]

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [18]:
np.linspace(10,100,5)

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [19]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

multi-dementional array

In [24]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
n = np.array([[1,2,3],[4,5,6],[7,8,9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
n[1,1]

np.int64(5)

In [30]:
n[1,1] = 20
n

array([[ 1,  2,  3],
       [ 4, 20,  6],
       [ 7,  8,  9]])

In [31]:
n[0]

array([1, 2, 3])

In [35]:
n[0]= [1,1,1]
n

array([[ 1,  1,  1],
       [ 4, 20,  6],
       [ 7,  8,  9]])

In [37]:
n[:,1]

array([ 1, 20,  8])

In [38]:
n[:]

array([[ 1,  1,  1],
       [ 4, 20,  6],
       [ 7,  8,  9]])

In [39]:
n[:,2] = [1,2,3]
n

array([[ 1,  1,  1],
       [ 4, 20,  2],
       [ 7,  8,  3]])

random generate arrays

In [46]:
np.random.rand(3,3)

array([[0.98910116, 0.6260922 , 0.18408451],
       [0.71954669, 0.0538542 , 0.65434844],
       [0.27028419, 0.78865403, 0.94318993]])

to set fix random generate we use random.seed(in this give any num that how many no u want to fix it may be 1 or 2 or all etc)

In [66]:
np.random.seed(2)

np.random.rand(3,3)

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482],
       [0.20464863, 0.61927097, 0.29965467]])

normsl distrubution add n in rand

In [67]:
np.random.seed(2)

np.random.randn(3,3)

array([[-0.41675785, -0.05626683, -2.1361961 ],
       [ 1.64027081, -1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809, -1.05795222]])

In [68]:
np.random.seed(2)

100 * np.random.rand(3,3)

array([[43.59949021,  2.59262318, 54.96624779],
       [43.53223926, 42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664, 29.96546737]])

In [70]:
np.random.seed(2)
np.random.randint(low =0,high=100,size =(3,3))

array([[40, 15, 72],
       [22, 43, 82],
       [75,  7, 34]])

element wise op

In [71]:
n =np.arange(5)
n

array([0, 1, 2, 3, 4])

In [72]:
n+1

array([1, 2, 3, 4, 5])

In [75]:
n+100

array([100, 101, 102, 103, 104])

In [77]:
(10 +(n*2))**2

array([100, 144, 196, 256, 324])

In [78]:
(10 +(n*2))**2  - 100

array([  0,  44,  96, 156, 224])

In [79]:
b = (10 +(n*2))**2  - 100
b

array([  0,  44,  96, 156, 224])

In [80]:
n+b

array([  0,  45,  98, 159, 228])

comparatioion arraya

In [81]:
n

array([0, 1, 2, 3, 4])

In [82]:
n >2

array([False, False, False,  True,  True])

In [83]:
n

array([0, 1, 2, 3, 4])

In [84]:
b

array([  0,  44,  96, 156, 224])

In [87]:
n < b

array([False,  True,  True,  True,  True])

restuen the true part valuw

In [88]:
n[n<b]

array([1, 2, 3, 4])

summarizinng operation

In [89]:
n

array([0, 1, 2, 3, 4])

In [90]:
n.min()

np.int64(0)

In [91]:
n.max()

np.int64(4)

In [92]:
n.sum()

np.int64(10)

In [93]:
n.mean()

np.float64(2.0)

In [95]:
n.sum()

np.int64(10)